print("My Personal Info")
print("Name: Marielle Angel Charishe M. Limbo")
print("Birthday: May 28, 2002")
print("Address: Brgy. Bantad, Sitio Bantauyan, Boac, Marinduque")
print("---------------------------------------------------------------------")
print("My Educational Background")
print("School: Marinduque State College")
print("Course: Bachelor of Science in Information Technology")
print("Year and Section: 2E")
print("---------------------------------------------------------------------")
print("My Hobbies")
print("1. Listening to music")
print("2. Singing")
print("3. Online games")
print("4. Taking care of my plants")
print("5. Cooking and baking")